language: c
only:
- master
- develop
matrix:
  include:
    - name: linux gcc 7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && sudo apt-get -y install python3 python3-pip"
        - BUILD=true
    - name: osx gcc 8
      os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
- eval "${MATRIX_EVAL}"
install:
- make -C test all
script:
- pip3 install setuptools wheel
- pip3 install simulaqron
- cd test
- ./test_using_simulaqron.sh
before_deploy:
- cd docs
- make build
- cd ..
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  committer_from_gh: true
  local_dir: docs/build/html
  on:
    branch: master
    condition: "$BUILD = True"
