language: c
only:
- master
- Develop
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get -y install python3 python3-pip
install:
- make -C test all
script:
- pip3 install setuptools wheel
- pip3 install simulaqron
- cd test
- ./test_using_simulaqron.sh
